### ISSUE TITLE
Add explicit auth_jwt_alg

### ISSUE THREAD

**Issue by r-chris** [maxx-t/nginx-jwt-module#4]
Should there maybe be an explicit (optional) `auth_jwt_alg` config setting to specify the expected algorithm for the JWT?

**Comment by maxx-t** [comment]
I am not against this idea, but I do not see the point.

**Comment by maxx-t** [comment]
Ok [I see now](https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/).

**Comment by maxx-t** [comment]
Done.
